name: Push Build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    if: ${{ contains(github.event.head_commit.message, '[build skip]') == false }}
    permissions:
      contents: write

    strategy:
      matrix:
        java: [21]
        os: ['ubuntu-latest']

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - uses: gradle/wrapper-validation-action@v3

      - name: Fix Gradle permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean buildAndGather --stacktrace --no-daemon

      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Read Properties info
        id: prop_info
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: "mod_version"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CarpetTubeAddition-${{ steps.prop_info.outputs.mod_version }}-${{ env.SHORT_SHA }}
          path: |
            versions/*/build/libs/
